version: "3.2"

networks:
  frontend:
  backend:

services:
  web:
    stdin_open: true
    tty: true
    image: apache
    build:
        context: ./apache
        dockerfile: Dockerfile
    container_name: web
    ports:
        - "8080:80"
    volumes:
        - guard_code:/var/www/html
        - apache_site:/etc/apache2/sites-enabled
        - ./apache/site/:/etc/apache2/sites-available
    depends_on:
        - mysql_guard
        - php
    environment:
        FPM_HOST: php:9000
    networks:
        - frontend
        - backend

  mysql_guard:
    image: mysql:5.7.29
    container_name: mysql_guard
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: guard
      MYSQL_USER: ${MYSQL_USER_GUARD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_GUARD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_GUARD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql_guard
    networks:
      - backend
    volumes:
      - mysql-guard:/var/lib/mysql
      
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - guard_code:/var/www/html
      - ./php/config/:/tmp/php-config/
    ports:
      - 9000:9000
      - 3000:3000
      - 3001:3001
      - 8081:8081
    networks:
      - backend
      - frontend

volumes:
  guard_code:
  mysql-guard:
  apache_site:
